# Esse arquivo values.yaml contem os valores defaults e pode ser utilizado como referencia para suas aplicações
# Adicionar o values.yaml no seu repositorio de aplicação, utilizando o seguinte padrão:
#   charts/<env>/values.yaml
#
projectName: deploy
namespace: "ns"
dockerRegistry: default-route-openshift-image-registry.apps.btvnd2hmlocp04.ops.hom.corp.btb
#imageStreamName: #Usar caso o imageStream seja diferente do nome de projectName
replicas:
  min: 1
  max: 2
containerPort: 8080
hostSuffix: apps.btvnd2hmlocp04.ops.hom.corp.btb
commonLabels: {}
commonAnnotations: {}
nodeSelector: {}
livenessProbe:
  enabled: false
  type: httpGet
  #command: []
  #failureThreshold: 3
  #path: /actuator/liveness
  #port: 8080
  #scheme: HTTP
  #initialDelaySeconds: 50
  #periodSeconds: 30
  #successThreshold: 1
  #timeoutSeconds: 30

readinessProbe:
  enabled: false
  type: httpGet
  # Baseado em comando....##
  #type: exec
  #command: ["/bin/sh", "-i", "-c", "echo 'Teste'" ]
  ###########################
  #failureThreshold: 3
  #path: /actuator/readiness
  #port: 8080
  #scheme: HTTP
  #initialDelaySeconds: 50
  #periodSeconds: 30
  #successThreshold: 1
  #timeoutSeconds: 30

resources:
  limits:
    cpu: 150m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi

secrets:
#  - name: SECURITY_OAUTH2_USERNAME
#    secretKeyRef:
#      key: SECURITY_OAUTH2_USERNAME
#      name: username
#  - name: SECURITY_OAUTH2_PASSWORD
#    secretKeyRef:
#      key: SECURITY_OAUTH2_PASSWORD
#      name: pwd-api

environment:
#  - name: TARGET_PORT
#    value: '8080'
#  - name: STAGE
#    value: 'HML'

metrics:
  cpu:
    enabled: true
    averageUtilization: 80
  memory:
    enabled: false
    averageUtilization: 80

enableHPA: true
enableDeployment: true
enableRoute: true
enableService: true
enableImageStream: false

apiVersions:
  hpa: autoscaling/v2
  deploymentConfig: apps.openshift.io/v1
  route: route.openshift.io/v1
  service: v1

enablePVC: false
VolumePersistence:
# Valores de nome de volume e pvc padrão (projectName)
#  - mountPath: /mnt/arquivos
#    size: 128Mi
# Definindo valores customizados
#  - name: app-name # Nome do pvc
#    mountPath: /mnt/arquivos
#    storageClassName: ocs-storagecluster-cephfs
#    volName: volume-5pcuk
#    size: 1G
#    volMode: Filesystem
#    ReadWriteMany: ReadWriteMany
#
# Caso a aplicação use empty Dir
enableEmptyDir: false
emptyDir:
#  - name: redis-1
#    mountPath: /data
#
strategy:
  type: Rolling
#  rollingParams:
#    intervalSeconds: 1
#    maxSurge: 50%
#    maxUnavailable: 50%
#    timeoutSeconds: 6000
#    updatePeriodSeconds: 1

securityContext:
  enabled: false
#  capabilities:
#    add: ["NET_BIND_SERVICE"]

