{{- if .Values.enableImageStream }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "project.name" . }}
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.dockerRegistry }}/{{ .Values.projectName }}:latest
      importPolicy: {}
      referencePolicy: {}
{{- end }}

