{{- if .Values.enablePVC }}
{{- range .Values.VolumePersistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name | default $.Values.projectName  }}
  namespace: {{ include "project.namespace" $ }}
  annotations:
    {{- include "common.annotations" $ | nindent 4 }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .size | default "1Gi" }}
  storageClassName: {{ .storageClassName | default "ocs-storagecluster-cephfs" }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
{{- end }}
{{- end }}
