{{- if .Values.enableService }}
apiVersion: {{ .Values.apiVersions.service }}
kind: Service
metadata:
  name: {{ include "project.name" . }}
  namespace: {{ include "project.namespace" . | required "[-] Requer passar o namespace no values.yaml" }}
  labels:
    app: {{ include "project.name" . }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- include "common.annotations" . | nindent 4 }}
spec:
  selector:
    app: {{ include "project.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
{{- end }}

